// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

using System;
using System.IO;
using System.Text;

using Stride.Graphics;
using Stride.Shaders;
using Stride.Shaders.Compiler;

namespace Stride.Assets.Effect;

/// <summary>
///   Helper class that can be used to write Effect bytecode into a source code file.
/// </summary>
public static class EffectBytecodeToSourceCodeWriter
{
    /// <summary>
    ///   Generates and writes C# source code for an Effect's bytecode as a static byte array field.
    /// </summary>
    /// <param name="name">
    ///   The name of the Effect.
    ///   Used for labeling and as a default class name if none is specified in the compiler parameters.
    /// </param>
    /// <param name="parameters">The compiler parameters used to compile the Effect.</param>
    /// <param name="bytecode">The Effect bytecode to be embedded in the generated source code as a byte array.</param>
    /// <param name="writer">
    ///   The text writer to which the generated C# source code is written. Must not be <see langword="null"/>.
    /// </param>
    /// <remarks>
    ///   The generated code is suitable for inclusion in a C# project to embed Effect bytecode
    ///   as a static field.
    /// </remarks>
    public static void Write(string name, CompilerParameters parameters, EffectBytecode bytecode, TextWriter writer)
    {
        var effectToGenerateText = new StringBuilder();
        effectToGenerateText.Append($"//     Effect [{name}]\r\n");

        var buffer = new MemoryStream();
        bytecode.WriteTo(buffer);

        var bufferAsText = new StringBuilder();
        var bufferArray = buffer.ToArray();
        for (int i = 0; i < bufferArray.Length; i++)
        {
            bufferAsText.Append(bufferArray[i]).Append(", ");
            if (i > 0 && (i % 64) == 0)
            {
                bufferAsText.AppendLine();
            }
        }

        var classDeclaration = parameters.Get(EffectSourceCodeKeys.ClassDeclaration);
        var fieldDeclaration = parameters.Get(EffectSourceCodeKeys.FieldDeclaration);
        var nameSpace = parameters.Get(EffectSourceCodeKeys.Namespace);
        var className = parameters.Get(EffectSourceCodeKeys.ClassName) ?? name;
        var fieldName = parameters.Get(EffectSourceCodeKeys.FieldName);

        var commandLine = string.Join(' ', Environment.GetCommandLineArgs());

        var graphicsPlatform = parameters.EffectParameters.Platform;

        string strideDefine = graphicsPlatform switch
        {
            GraphicsPlatform.Direct3D11 or
            GraphicsPlatform.Direct3D12 => "STRIDE_GRAPHICS_API_DIRECT3D",
            GraphicsPlatform.OpenGL => "STRIDE_GRAPHICS_API_OPENGLCORE",
            GraphicsPlatform.OpenGLES => "STRIDE_GRAPHICS_API_OPENGLES",
            GraphicsPlatform.Vulkan => "STRIDE_GRAPHICS_API_VULKAN",

            _ => "undefined"
        };

        string codeTemplate = $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     Stride Effect Compiler File Generated:
            {{effectToGenerateText}}//
            //     Command Line: {{commandLine}}
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            #if {{strideDefine}}

            namespace {{nameSpace}}
            {
                {{classDeclaration}} class {{className}}
                {
                    {{fieldDeclaration}} static readonly byte[] {{fieldName}} = new byte[] {
            {{bufferAsText}}
                    };
                }
            }

            #endif

            """;
        writer.Write(codeTemplate);
        writer.Flush();
    }
}
