// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.
using System;
using System.IO;
using System.Runtime.InteropServices;

namespace Stride.Core
{
    /// <summary>
    /// Helper class to find executable (usually in folder tools/TFM) from a .NET Core library (usually in folder lib/TFM).
    /// This follow the layout generated by Stride.NuGetLoader that is shipped with every executable project such as GameStudio, Asset Compiler, Connection router, etc.
    /// </summary>
    static class LoaderToolLocator
    {
        private static readonly bool IsWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);

        // Windows executables carry ".exe"; .NET apphosts on Linux/macOS have no extension.
        private static readonly string ExeExtension = IsWindows ? ".exe" : string.Empty;

        internal static string GetExecutable(string assemblyLocation)
        {
            // Already an executable (Windows .exe, or Unix apphost with no extension)
            var inputExt = Path.GetExtension(assemblyLocation);
            if (IsWindows)
            {
                if (inputExt.Equals(".exe", StringComparison.OrdinalIgnoreCase))
                    return assemblyLocation;
            }
            else if (string.IsNullOrEmpty(inputExt))
            {
                return assemblyLocation;
            }

            // Same folder (dev or old layout in nuget package): swap .dll for the platform executable form
            {
                var exeLocation = Path.ChangeExtension(assemblyLocation, ExeExtension);
                if (File.Exists(exeLocation))
                    return exeLocation;
            }

            // Remap lib/<TFM> to tools/<TFM> (nuget package layout)
            var tfmPath = Path.GetDirectoryName(assemblyLocation);
            if (tfmPath != null)
            {
                var parentPath = Path.GetDirectoryName(tfmPath);
                if (parentPath != null && Path.GetFileName(parentPath).Equals("lib", StringComparison.Ordinal))
                {
                    var packageRoot = Path.GetDirectoryName(parentPath);
                    if (packageRoot != null)
                    {
                        var tfm = Path.GetFileName(tfmPath);
                        var exeName = Path.GetFileNameWithoutExtension(assemblyLocation) + ExeExtension;
                        var exeLocation = Path.Combine(packageRoot, "tools", tfm, exeName);
                        if (File.Exists(exeLocation))
                            return exeLocation;
                    }
                }
            }

            throw new FileNotFoundException($"Could not find executable to start assembly [{assemblyLocation}]");
        }
    }
}
