#if XENKO_GRAPHICS_API_NULL 
//------------------------------------------------------------------------------
// <auto-generated>
//     Xenko Effect Compiler File Generated:
//     Effect [UIEffect]
//
//     Command Line: C:\work\Stash\Xenko\sources\engine\Xenko.Graphics\Shaders.Bytecodes\..\..\..\..\Bin\Windows-Direct3D11\Xenko.Core.Assets.CompilerApp.exe --profile=Windows-Null --platform=Windows --output-path=C:\work\Stash\Xenko\sources\engine\Xenko.Graphics\Shaders.Bytecodes\obj\app_data --build-path=C:\work\Stash\Xenko\sources\engine\Xenko.Graphics\Shaders.Bytecodes\obj\build_app_data --package-file=Graphics.xkpkg
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenko.Graphics 
{
    internal partial class UIEffect
    {
        private static readonly byte[] binaryBytecode = new byte[] {
        };
    }
}
#endif
