//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irony {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Irony.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string ConsoleNoChars {
            get {
                return ResourceManager.GetString("ConsoleNoChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string ConsoleYesChars {
            get {
                return ResourceManager.GetString("ConsoleYesChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法不明确，无法解决的归约冲突。 状态{0}，前瞻[{1}] 的本地化字符串。
        /// </summary>
        internal static string ErrAmbigGrammarRR {
            get {
                return ResourceManager.GetString("ErrAmbigGrammarRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法模棱两可，无法解决的移位减少冲突。 状态{0}，前瞻[{1}] 的本地化字符串。
        /// </summary>
        internal static string ErrAmbigGrammarSR {
            get {
                return ResourceManager.GetString("ErrAmbigGrammarSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在堆栈中找不到参数列表。 预期：ValueList，找到：{0}。 的本地化字符串。
        /// </summary>
        internal static string ErrArgListNotFound {
            get {
                return ResourceManager.GetString("ErrArgListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的操作，尝试分配常量或文字值。 的本地化字符串。
        /// </summary>
        internal static string ErrAssignLiteralValue {
            get {
                return ResourceManager.GetString("ErrAssignLiteralValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符文字的长度无效-应该为单个字符。 的本地化字符串。
        /// </summary>
        internal static string ErrBadChar {
            get {
                return ResourceManager.GetString("ErrBadChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式不正确的字符串文字-无法找到终止符号。 的本地化字符串。
        /// </summary>
        internal static string ErrBadStrLiteral {
            get {
                return ResourceManager.GetString("ErrBadStrLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的unicode转义（{0}），应为{1}十六进制数字。 的本地化字符串。
        /// </summary>
        internal static string ErrBadUnEscape {
            get {
                return ResourceManager.GetString("ErrBadUnEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \x转义无效，至少应为一位数字。 的本地化字符串。
        /// </summary>
        internal static string ErrBadXEscape {
            get {
                return ResourceManager.GetString("ErrBadXEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将值从类型{0}转换为类型{1}，类型转换器未定义。 的本地化字符串。
        /// </summary>
        internal static string ErrCannotConvertValue {
            get {
                return ResourceManager.GetString("ErrCannotConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将文字{0}转换为类型{1}。 的本地化字符串。
        /// </summary>
        internal static string ErrCannotConvertValueToType {
            get {
                return ResourceManager.GetString("ErrCannotConvertValueToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}输入的状态{1}：{2} 的本地化字符串。
        /// </summary>
        internal static string ErrConflictMsgTemplate {
            get {
                return ResourceManager.GetString("ErrConflictMsgTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 致命错误： 的本地化字符串。
        /// </summary>
        internal static string ErrConsoleFatalError {
            get {
                return ResourceManager.GetString("ErrConsoleFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言实现尚不支持构造&apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string ErrConstructNotSupported {
            get {
                return ResourceManager.GetString("ErrConstructNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到引用值的右引号。 的本地化字符串。
        /// </summary>
        internal static string ErrDsvNoClosingQuote {
            get {
                return ResourceManager.GetString("ErrDsvNoClosingQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则表达式的开关{0}重复。 的本地化字符串。
        /// </summary>
        internal static string ErrDupRegexSwitch {
            get {
                return ResourceManager.GetString("ErrDupRegexSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串文本[{1}中的起始符号{0}重复。 的本地化字符串。
        /// </summary>
        internal static string ErrDupStartSymbolStr {
            get {
                return ResourceManager.GetString("ErrDupStartSymbolStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法为非终端[{0}创建ast节点，错误：{1} 的本地化字符串。
        /// </summary>
        internal static string ErrFailedCreateNode {
            get {
                return ResourceManager.GetString("ErrFailedCreateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImpliedSymbolTerminal不能用于设置了DisableScannerParserLink标志的语法中 的本地化字符串。
        /// </summary>
        internal static string ErrImpliedOpUseParserLink {
            get {
                return ResourceManager.GetString("ErrImpliedOpUseParserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解释器错误，datastack.pop()操作失败-堆栈为空。 的本地化字符串。
        /// </summary>
        internal static string ErrInternalErrDataPopFailed {
            get {
                return ResourceManager.GetString("ErrInternalErrDataPopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译很忙。 的本地化字符串。
        /// </summary>
        internal static string ErrInterpreterIsBusy {
            get {
                return ResourceManager.GetString("ErrInterpreterIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IncDecNode AST节点的参数无效：第一个或第二个参数应为“--”或“ ++”。 的本地化字符串。
        /// </summary>
        internal static string ErrInvalidArgsForIncDec {
            get {
                return ResourceManager.GetString("ErrInvalidArgsForIncDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用Evaluate方法时无效的AstMode值。 节点：{0}，方式：{1}。 的本地化字符串。
        /// </summary>
        internal static string ErrInvalidAstMode {
            get {
                return ResourceManager.GetString("ErrInvalidAstMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效字符： &apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string ErrInvalidChar {
            get {
                return ResourceManager.GetString("ErrInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的嵌入式表达式。 的本地化字符串。
        /// </summary>
        internal static string ErrInvalidEmbeddedPrefix {
            get {
                return ResourceManager.GetString("ErrInvalidEmbeddedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的dedent级别，找不到以前匹配的缩进。 的本地化字符串。
        /// </summary>
        internal static string ErrInvDedent {
            get {
                return ResourceManager.GetString("ErrInvDedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的转义序列：\{0}。 的本地化字符串。
        /// </summary>
        internal static string ErrInvEscape {
            get {
                return ResourceManager.GetString("ErrInvEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的转义序列。 的本地化字符串。
        /// </summary>
        internal static string ErrInvEscSeq {
            get {
                return ResourceManager.GetString("ErrInvEscSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的转义符号，仅应为&apos;u&apos;或&apos;U&apos;。 的本地化字符串。
        /// </summary>
        internal static string ErrInvEscSymbol {
            get {
                return ResourceManager.GetString("ErrInvEscSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效号码。 的本地化字符串。
        /// </summary>
        internal static string ErrInvNumber {
            get {
                return ResourceManager.GetString("ErrInvNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规表达式无效的选项&apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ErrInvRegexSwitch {
            get {
                return ResourceManager.GetString("ErrInvRegexSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串文字[{0}]中的错误：未指定开始/结束符号。 的本地化字符串。
        /// </summary>
        internal static string ErrInvStrDef {
            get {
                return ResourceManager.GetString("ErrInvStrDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含SyntaxError的生产的最后一项必须是终端。 非终端：{0} 的本地化字符串。
        /// </summary>
        internal static string ErrLastTermOfErrorProd {
            get {
                return ResourceManager.GetString("ErrLastTermOfErrorProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列出非终端不能标记为瞬态； 清单：（{0}） 的本地化字符串。
        /// </summary>
        internal static string ErrListCannotBeTransient {
            get {
                return ResourceManager.GetString("ErrListCannotBeTransient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预期换行。 的本地化字符串。
        /// </summary>
        internal static string ErrNewLineExpected {
            get {
                return ResourceManager.GetString("ErrNewLineExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NLALR进程处于不确定循环中，状态数超过3000。 的本地化字符串。
        /// </summary>
        internal static string ErrNLALRhang {
            get {
                return ResourceManager.GetString("ErrNLALRhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有用于打开符号{0}的闭合对 的本地化字符串。
        /// </summary>
        internal static string ErrNoClosingBrace {
            get {
                return ResourceManager.GetString("ErrNoClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告：未在非终端{0}上设置AstNodeType或AstNodeCreator。 的本地化字符串。
        /// </summary>
        internal static string ErrNodeTypeNotSetOn {
            get {
                return ResourceManager.GetString("ErrNodeTypeNotSetOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则表达式文字没有结束符号。 的本地化字符串。
        /// </summary>
        internal static string ErrNoEndForRegex {
            get {
                return ResourceManager.GetString("ErrNoEndForRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在嵌入式表达式中找不到结尾标记&apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string ErrNoEndTagInEmbExpr {
            get {
                return ResourceManager.GetString("ErrNoEndTagInEmbExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnExprNode：一元运算符&apos;{0}&apos;没有实现。 的本地化字符串。
        /// </summary>
        internal static string ErrNoImplForUnaryOp {
            get {
                return ResourceManager.GetString("ErrNoImplForUnaryOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字后不能跟字母。 的本地化字符串。
        /// </summary>
        internal static string ErrNoLetterAfterNum {
            get {
                return ResourceManager.GetString("ErrNoLetterAfterNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ParserDataBuilder错误：状态{0}不充分，减少项&apos;{1}&apos;没有提前。 的本地化字符串。
        /// </summary>
        internal static string ErrNoLkhds {
            get {
                return ResourceManager.GetString("ErrNoLkhds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非终结符{0}具有未初始化的Rule属性。 的本地化字符串。
        /// </summary>
        internal static string ErrNtRuleIsNull {
            get {
                return ResourceManager.GetString("ErrNtRuleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试评估NULL AST节点。 解析期间未创建术语“ {0}”的AST节点。 的本地化字符串。
        /// </summary>
        internal static string ErrNullNodeEval {
            get {
                return ResourceManager.GetString("ErrNullNodeEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有为类型{1}和{2}定义运算符&apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string ErrOpNotDefinedForTypes {
            get {
                return ResourceManager.GetString("ErrOpNotDefinedForTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未实现运算符&apos;{0}。 的本地化字符串。
        /// </summary>
        internal static string ErrOpNotImplemented {
            get {
                return ResourceManager.GetString("ErrOpNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string ErrOutErrorPrintFormat {
            get {
                return ResourceManager.GetString("ErrOutErrorPrintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeOutlineFilter：行继续符号&apos;{0}&apos;应该添加到Grammar.NonGrammarTerminals列表中。 的本地化字符串。
        /// </summary>
        internal static string ErrOutlineFilterContSymbol {
            get {
                return ResourceManager.GetString("ErrOutlineFilterContSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法错误，预期为：{0} 的本地化字符串。
        /// </summary>
        internal static string ErrParserUnexpInput {
            get {
                return ResourceManager.GetString("ErrParserUnexpInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析树为空，无法求值。 的本地化字符串。
        /// </summary>
        internal static string ErrParseTreeNull {
            get {
                return ResourceManager.GetString("ErrParseTreeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析树根节点为空，无法求值。 的本地化字符串。
        /// </summary>
        internal static string ErrParseTreeRootNull {
            get {
                return ResourceManager.GetString("ErrParseTreeRootNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根AST节点为空，无法评估。 的本地化字符串。
        /// </summary>
        internal static string ErrRootAstNodeNull {
            get {
                return ResourceManager.GetString("ErrRootAstNodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根AST节点未实现IInterpretedAstNode接口，无法评估。 的本地化字符串。
        /// </summary>
        internal static string ErrRootAstNoInterface {
            get {
                return ResourceManager.GetString("ErrRootAstNoInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作为“路由”参数传递给解析器的（{0}）术语不是语法的根或代码根。 将其添加到语法构造函数中设置的SnippetRoots中。 的本地化字符串。
        /// </summary>
        internal static string ErrRootNotRegistered {
            get {
                return ResourceManager.GetString("ErrRootNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法的根属性未设置。 的本地化字符串。
        /// </summary>
        internal static string ErrRootNotSet {
            get {
                return ResourceManager.GetString("ErrRootNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减少冲突。 状态{0}，前瞻性：{1}。 在冲突集中选择第一个生产的减少。 的本地化字符串。
        /// </summary>
        internal static string ErrRRConflict {
            get {
                return ResourceManager.GetString("ErrRRConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非终端{0}的规则在生产之一中的位置{1}处包含null作为操作数。 的本地化字符串。
        /// </summary>
        internal static string ErrRuleContainsNull {
            get {
                return ResourceManager.GetString("ErrRuleContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift减少冲突。 状态{0}，前瞻[{1}]。 选择班次作为首选操作。 的本地化字符串。
        /// </summary>
        internal static string ErrSRConflict {
            get {
                return ResourceManager.GetString("ErrSRConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法错误。 的本地化字符串。
        /// </summary>
        internal static string ErrSyntaxErrorNoInfo {
            get {
                return ResourceManager.GetString("ErrSyntaxErrorNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板字符串文字[{0}]中模板设置（AstNodeConfig属性）中的表达式根非终结符未添加到根集。 将其添加到语法构造函数中的SnippetRoots中。 的本地化字符串。
        /// </summary>
        internal static string ErrTemplExprNotRoot {
            get {
                return ResourceManager.GetString("ErrTemplExprNotRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未在模板字符串文字[{0}]的模板设置（AstNode Config属性）中指定表达式根。 的本地化字符串。
        /// </summary>
        internal static string ErrTemplMissingExprRoot {
            get {
                return ResourceManager.GetString("ErrTemplMissingExprRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串文字[{0}]中的错误：设置了IsTemplate标志，但AstNodeConfig属性中未提供TemplateSettings。 的本地化字符串。
        /// </summary>
        internal static string ErrTemplNoSettings {
            get {
                return ResourceManager.GetString("ErrTemplNoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端{0}的前缀为空。 的本地化字符串。
        /// </summary>
        internal static string ErrTerminalHasEmptyPrefix {
            get {
                return ResourceManager.GetString("ErrTerminalHasEmptyPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时非终端必须有零个或一个非标点子节点；非终端：{0}。 的本地化字符串。
        /// </summary>
        internal static string ErrTransientNtMustHaveOneTerm {
            get {
                return ResourceManager.GetString("ErrTransientNtMustHaveOneTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未关闭的注释块 的本地化字符串。
        /// </summary>
        internal static string ErrUnclosedComment {
            get {
                return ResourceManager.GetString("ErrUnclosedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意外的文件结尾。 的本地化字符串。
        /// </summary>
        internal static string ErrUnexpEof {
            get {
                return ResourceManager.GetString("ErrUnexpEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意外缩进。 的本地化字符串。
        /// </summary>
        internal static string ErrUnexpIndent {
            get {
                return ResourceManager.GetString("ErrUnexpIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右大括号{0}不匹配。 的本地化字符串。
        /// </summary>
        internal static string ErrUnmatchedCloseBrace {
            get {
                return ResourceManager.GetString("ErrUnmatchedCloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量{0}不是可调用函数。 的本地化字符串。
        /// </summary>
        internal static string ErrVarIsNotCallable {
            get {
                return ResourceManager.GetString("ErrVarIsNotCallable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量{0}未定义。 的本地化字符串。
        /// </summary>
        internal static string ErrVarNotDefined {
            get {
                return ResourceManager.GetString("ErrVarNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数数量无效。 预期为{0}，找到为{1}。 的本地化字符串。
        /// </summary>
        internal static string ErrWrongArgCount {
            get {
                return ResourceManager.GetString("ErrWrongArgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1}:{2}) 的本地化字符串。
        /// </summary>
        internal static string FmtRowCol {
            get {
                return ResourceManager.GetString("FmtRowCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受 的本地化字符串。
        /// </summary>
        internal static string LabelActionAccept {
            get {
                return ResourceManager.GetString("LabelActionAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运算符，移至{0} /在{1}上减小。 的本地化字符串。
        /// </summary>
        internal static string LabelActionOp {
            get {
                return ResourceManager.GetString("LabelActionOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减少{0} 的本地化字符串。
        /// </summary>
        internal static string LabelActionReduce {
            get {
                return ResourceManager.GetString("LabelActionReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移至{0} 的本地化字符串。
        /// </summary>
        internal static string LabelActionShift {
            get {
                return ResourceManager.GetString("LabelActionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （未知动作类型） 的本地化字符串。
        /// </summary>
        internal static string LabelActionUnknown {
            get {
                return ResourceManager.GetString("LabelActionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (读取结束) 的本地化字符串。
        /// </summary>
        internal static string LabelEofMark {
            get {
                return ResourceManager.GetString("LabelEofMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [声明结尾] 的本地化字符串。
        /// </summary>
        internal static string LabelEosLabel {
            get {
                return ResourceManager.GetString("LabelEosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （初始状态） 的本地化字符串。
        /// </summary>
        internal static string LabelInitialState {
            get {
                return ResourceManager.GetString("LabelInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （关键符号） 的本地化字符串。
        /// </summary>
        internal static string LabelKeySymbol {
            get {
                return ResourceManager.GetString("LabelKeySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （关键词） 的本地化字符串。
        /// </summary>
        internal static string LabelKeyword {
            get {
                return ResourceManager.GetString("LabelKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [越线] 的本地化字符串。
        /// </summary>
        internal static string LabelLineBreak {
            get {
                return ResourceManager.GetString("LabelLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置： 的本地化字符串。
        /// </summary>
        internal static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        internal static string LabelSrcHaveMore {
            get {
                return ResourceManager.GetString("LabelSrcHaveMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （未分配） 的本地化字符串。
        /// </summary>
        internal static string LabelUnassigned {
            get {
                return ResourceManager.GetString("LabelUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （未命名） 的本地化字符串。
        /// </summary>
        internal static string LabelUnnamed {
            get {
                return ResourceManager.GetString("LabelUnnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中止脚本(是/否)? 的本地化字符串。
        /// </summary>
        internal static string MsgAbortScriptYN {
            get {
                return ResourceManager.GetString("MsgAbortScriptYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}控制台。\r\n按Ctrl-C退出程序。\r\n 的本地化字符串。
        /// </summary>
        internal static string MsgDefaultConsoleGreeting {
            get {
                return ResourceManager.GetString("MsgDefaultConsoleGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制台 的本地化字符串。
        /// </summary>
        internal static string MsgDefaultConsoleTitle {
            get {
                return ResourceManager.GetString("MsgDefaultConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出控制台(是/否)? 的本地化字符串。
        /// </summary>
        internal static string MsgExitConsoleYN {
            get {
                return ResourceManager.GetString("MsgExitConsoleYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NLALR转换：在‘.’中添加WrapTail()  [{0}]的位置。 的本地化字符串。
        /// </summary>
        internal static string MsgNLALRAdvice {
            get {
                return ResourceManager.GetString("MsgNLALRAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键结束程序。 的本地化字符串。
        /// </summary>
        internal static string MsgPressAnyKeyToExit {
            get {
                return ResourceManager.GetString("MsgPressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;[{0}], 在 {1} 的本地化字符串。
        /// </summary>
        internal static string MsgSrcPosToString {
            get {
                return ResourceManager.GetString("MsgSrcPosToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析冲突已在代码中解决。 的本地化字符串。
        /// </summary>
        internal static string MsgTraceConflictResolved {
            get {
                return ResourceManager.GetString("MsgTraceConflictResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运算符-解析为{0} 的本地化字符串。
        /// </summary>
        internal static string MsgTraceOpResolved {
            get {
                return ResourceManager.GetString("MsgTraceOpResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从堆栈弹出状态，推入{0} 的本地化字符串。
        /// </summary>
        internal static string MsgTracePoppedState {
            get {
                return ResourceManager.GetString("MsgTracePoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在恢复：{0} 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecoverAction {
            get {
                return ResourceManager.GetString("MsgTraceRecoverAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法恢复 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecoverFailed {
            get {
                return ResourceManager.GetString("MsgTraceRecoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在恢复：发现状态，发生错误时转移：{0} 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecoverFoundState {
            get {
                return ResourceManager.GetString("MsgTraceRecoverFoundState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复：弹出堆栈，查找有错误移位的状态 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecovering {
            get {
                return ResourceManager.GetString("MsgTraceRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复：减少错误产生的时间。 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecoverReducing {
            get {
                return ResourceManager.GetString("MsgTraceRecoverReducing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复：移位误差项，{0} 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecoverShiftError {
            get {
                return ResourceManager.GetString("MsgTraceRecoverShiftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复：转移到错误产生结束为止。 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecoverShiftTillEnd {
            get {
                return ResourceManager.GetString("MsgTraceRecoverShiftTillEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已恢复 的本地化字符串。
        /// </summary>
        internal static string MsgTraceRecoverSuccess {
            get {
                return ResourceManager.GetString("MsgTraceRecoverSuccess", resourceCulture);
            }
        }
    }
}
