// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org/ & https://stride3d.net)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

// Generates the TextMate assets this VSIX ships to colorize .sdsl/.sdfx files — Grammars/sdsl.tmLanguage.json
// plus its companion sdsl.tmLanguage.tmTheme (which maps the grammar's scopes to VS classification types) — from
// Stride's own shader vocabulary, so the coloring never drifts from the language. Rerun after the shader
// keyword/type list changes, and commit the result.
//
// The keyword/type lists live in Stride.Shaders.Parsing.SDSL.Reserved (Stride.Shaders.Parsers). They're built
// at runtime in a static constructor (loops that expand float -> float4, float4x4, ...), so this reflects the
// *built* assembly and reads the finished sets rather than trying to parse the source. Only the vocabulary is
// generated; the structural rules (comments/strings/numbers) are the hand-written template below.
//
// Run it as a .NET 10 file-based app (no project needed):
//   dotnet run sources/tools/Stride.VisualStudio.Package.Shaders/generate-sdsl-grammar.cs
// It finds a built Stride.Shaders.Parsers.dll under sources/shaders automatically, or takes one as an argument:
//   dotnet run .../generate-sdsl-grammar.cs -- "path/to/Stride.Shaders.Parsers.dll"

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

var scriptDir = ScriptDirectory();
var repoRoot = FindRepoRoot(scriptDir);

var dllPath = args.Length > 0 ? args[0] : LocateParsersAssembly(repoRoot);
if (dllPath is null || !File.Exists(dllPath))
{
    Console.Error.WriteLine(
        "Could not find a built Stride.Shaders.Parsers.dll. Build Stride.Shaders.Parsers (or the engine) first, " +
        "or pass the assembly path: dotnet run generate-sdsl-grammar.cs -- <path-to-dll>");
    return 1;
}

Console.WriteLine($"Reading SDSL vocabulary from {dllPath}");

// Reflect the two vocabulary sets. The type is public; the fields are internal, so read them with reflection.
var assembly = Assembly.LoadFrom(dllPath);
var reserved = assembly.GetType("Stride.Shaders.Parsing.SDSL.Reserved", throwOnError: true)!;
var typeNames = ReadStringSet(reserved, "TypeNames");
var keywords = ReadStringSet(reserved, "Keywords");

// Types = the numbered scalar/vector/matrix names plus the bare scalars they derive from (float alongside
// float4), so they colour consistently. Everything else reserved is a keyword.
var types = new SortedSet<string>(typeNames, StringComparer.Ordinal);
foreach (var name in typeNames)
{
    var baseName = Regex.Match(name, @"^(.*?)\d+(x\d+)?$");
    if (baseName.Success && keywords.Contains(baseName.Groups[1].Value))
        types.Add(baseName.Groups[1].Value);
}
var keywordOnly = new SortedSet<string>(keywords.Except(types), StringComparer.Ordinal);

Console.WriteLine($"  {types.Count} types, {keywordOnly.Count} keywords");

var grammar = BuildGrammar(types, keywordOnly);
var grammarPath = Path.Combine(scriptDir, "Grammars", "sdsl.tmLanguage.json");
File.WriteAllText(grammarPath, grammar.ToJsonString(new JsonSerializerOptions
{
    WriteIndented = true,
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
}) + Environment.NewLine);
Console.WriteLine($"Wrote {grammarPath}");

// VS pairs the theme with the grammar by filename base (sdsl.tmLanguage.*) and uses it to map scopes to colours.
var themePath = Path.Combine(scriptDir, "Grammars", "sdsl.tmLanguage.tmTheme");
File.WriteAllText(themePath, BuildTheme());
Console.WriteLine($"Wrote {themePath}");
return 0;

static SortedSet<string> ReadStringSet(Type type, string fieldName)
{
    var field = type.GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Static)
        ?? throw new InvalidOperationException($"{type.FullName}.{fieldName} not found (did the vocabulary move?).");
    var values = (IEnumerable<string>)field.GetValue(null)!;
    return new SortedSet<string>(values, StringComparer.Ordinal);
}

// The grammar: hand-written structural rules (comments/strings/numbers) + the two generated vocabulary matches.
static JsonObject BuildGrammar(SortedSet<string> types, SortedSet<string> keywords) => new()
{
    ["information_for_contributors"] = new JsonArray(
        "Generated by generate-sdsl-grammar.cs from Stride.Shaders.Parsing.SDSL.Reserved.",
        "Do not edit the types/keywords matches by hand — rerun the generator to update them."),
    ["name"] = "Stride Shader Language",
    ["scopeName"] = "source.sdsl",
    ["fileTypes"] = new JsonArray("sdsl", "sdfx"),
    ["patterns"] = new JsonArray(
        Include("#comments"),
        Include("#strings"),
        Include("#numbers"),
        Include("#types"),
        Include("#keywords")),
    ["repository"] = new JsonObject
    {
        ["comments"] = new JsonObject
        {
            ["patterns"] = new JsonArray(
                new JsonObject { ["name"] = "comment.line.double-slash.sdsl", ["match"] = @"//.*$" },
                new JsonObject { ["name"] = "comment.block.sdsl", ["begin"] = @"/\*", ["end"] = @"\*/" }),
        },
        ["strings"] = new JsonObject
        {
            ["name"] = "string.quoted.double.sdsl",
            ["begin"] = "\"",
            ["end"] = "\"",
            ["patterns"] = new JsonArray(new JsonObject { ["name"] = "constant.character.escape.sdsl", ["match"] = @"\\." }),
        },
        ["numbers"] = new JsonObject
        {
            ["name"] = "constant.numeric.sdsl",
            ["match"] = @"\b(0[xX][0-9a-fA-F]+|\d+\.?\d*([eE][+-]?\d+)?)[fFhHlLuU]*\b",
        },
        ["types"] = Words(types, "storage.type.sdsl"),
        ["keywords"] = Words(keywords, "keyword.other.sdsl"),
    },
};

static JsonObject Include(string reference) => new() { ["include"] = reference };

static JsonObject Words(IEnumerable<string> words, string scope) => new()
{
    ["name"] = scope,
    ["match"] = $@"\b({string.Join("|", words.Select(Regex.Escape))})\b",
};

// The companion colour theme: maps the scopes BuildGrammar emits (by scope prefix) to VS classification types.
// Kept next to the grammar so the mapping can't drift from the scope names above.
static string BuildTheme()
{
    (string Scopes, string Classification)[] rules =
    [
        ("keyword, storage.type", "keyword"),
        ("string, constant.character.escape", "string"),
        ("constant.numeric", "number"),
        ("comment", "comment"),
    ];

    var sb = new StringBuilder();
    sb.AppendLine("""<?xml version="1.0" encoding="UTF-8"?>""");
    sb.AppendLine("""<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">""");
    sb.AppendLine("<!-- Generated by generate-sdsl-grammar.cs; maps sdsl.tmLanguage.json's scopes to VS classifications. -->");
    sb.AppendLine("""<plist version="1.0">""");
    sb.AppendLine("  <dict>");
    sb.AppendLine("    <key>name</key>");
    sb.AppendLine("    <string>SDSL Theme</string>");
    sb.AppendLine("    <key>settings</key>");
    sb.AppendLine("    <array>");
    foreach (var (scopes, classification) in rules)
    {
        sb.AppendLine("      <dict>");
        sb.AppendLine("        <key>scope</key>");
        sb.AppendLine($"        <string>{scopes}</string>");
        sb.AppendLine("        <key>settings</key>");
        sb.AppendLine("        <dict>");
        sb.AppendLine("          <key>vsclassificationtype</key>");
        sb.AppendLine($"          <string>{classification}</string>");
        sb.AppendLine("        </dict>");
        sb.AppendLine("      </dict>");
    }
    sb.AppendLine("    </array>");
    sb.AppendLine("    <key>uuid</key>");
    sb.AppendLine("    <string>5B8C1E7A-3D2F-4A9B-8E6C-1F0A2B3C4D5E</string>");
    sb.AppendLine("  </dict>");
    sb.AppendLine("</plist>");
    return sb.ToString();
}

static string ScriptDirectory([CallerFilePath] string path = "") => Path.GetDirectoryName(path)!;

// Walk up to the repository root (the directory that holds the sources/ tree).
static string FindRepoRoot(string start)
{
    for (var dir = new DirectoryInfo(start); dir is not null; dir = dir.Parent)
        if (Directory.Exists(Path.Combine(dir.FullName, "sources")))
            return dir.FullName;
    throw new DirectoryNotFoundException($"Could not find the repository root above '{start}'.");
}

// Newest net10.0 (non-Android) build of Stride.Shaders.Parsers.dll under sources/shaders.
static string? LocateParsersAssembly(string repoRoot)
{
    var searchRoot = Path.Combine(repoRoot, "sources", "shaders", "Stride.Shaders.Parsers", "bin");
    if (!Directory.Exists(searchRoot))
        return null;

    return Directory.EnumerateFiles(searchRoot, "Stride.Shaders.Parsers.dll", SearchOption.AllDirectories)
        .Where(path => path.Contains($"{Path.DirectorySeparatorChar}net10.0{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
            && !path.Contains("android", StringComparison.OrdinalIgnoreCase)
            && !path.Contains($"{Path.DirectorySeparatorChar}ref{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
            && !path.Contains($"{Path.DirectorySeparatorChar}refint{Path.DirectorySeparatorChar}", StringComparison.Ordinal))
        .OrderByDescending(File.GetLastWriteTimeUtc)
        .FirstOrDefault();
}
