// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class VoxelStorageTextureClipmapShaderKeys
    {
        public static readonly ValueParameterKey<Vector4> perMapOffsetScale = ParameterKeys.NewValue<Vector4>();
        public static readonly ObjectParameterKey<Texture> clipMaps = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> mipMaps = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> LinearBorderSampler3D = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> LinearBorderSampler3D_NearestMip = ParameterKeys.NewObject<SamplerState>();
    }
}
