// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

using Xenko.Rendering.Data;
using Xenko.Shaders.Compiler;
namespace XenkoEffects
{
    [DataContract]public partial class PreviewTextureParameters : ShaderMixinParameters
    {
        public static readonly PermutationParameterKey<bool> Is3D = ParameterKeys.NewPermutation<bool>();
    };
    internal static partial class ShaderMixins
    {
        internal partial class PreviewTexture  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                if (context.GetParam(PreviewTextureParameters.Is3D))
                {
                    context.Mixin(mixin, "Sprite3DBase");
                }
                context.Mixin(mixin, "SpriteBatch");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("PreviewTexture", new PreviewTexture());
            }
        }
    }
}
