//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenko.Graphics {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrameworkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xenko.Graphics.FrameworkResources", typeof(FrameworkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 默认渲染目标已创建 的本地化字符串。
        /// </summary>
        internal static string CannotCreateDefaultRenderTarget {
            get {
                return ResourceManager.GetString("CannotCreateDefaultRenderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法确定当前的显示模式 的本地化字符串。
        /// </summary>
        internal static string CurrentDisplayModeNotFound {
            get {
                return ResourceManager.GetString("CurrentDisplayModeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]图形资源已设置 的本地化字符串。
        /// </summary>
        internal static string GraphicsResourceAlreadySet {
            get {
                return ResourceManager.GetString("GraphicsResourceAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法在已绑定的[{0}]图形资源上设置属性 的本地化字符串。
        /// </summary>
        internal static string GraphicsResourceStateBound {
            get {
                return ResourceManager.GetString("GraphicsResourceStateBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有默认的渲染目标。 使用GraphicsDevice.InitDefaultRenderTarget()。 的本地化字符串。
        /// </summary>
        internal static string NoDefaultRenterTarget {
            get {
                return ResourceManager.GetString("NoDefaultRenterTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前在此GraphicsDevice上没有设置深度/模板缓冲区。 的本地化字符串。
        /// </summary>
        internal static string NoDepthStencilBufferBound {
            get {
                return ResourceManager.GetString("NoDepthStencilBufferBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前没有可用的GraphicsDevice。 检查GraphicsDevice.Current不应该为null 的本地化字符串。
        /// </summary>
        internal static string NoGraphicsDeviceAvailable {
            get {
                return ResourceManager.GetString("NoGraphicsDeviceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有模板缓冲区格式[{0}]的情况下无法清除模板缓冲区 的本地化字符串。
        /// </summary>
        internal static string NoStencilBufferForDepthFormat {
            get {
                return ResourceManager.GetString("NoStencilBufferForDepthFormat", resourceCulture);
            }
        }
    }
}
