// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class ChapmanBlurShaderKeys
    { 
        public static readonly ValueParameterKey<float> u_BlurRadius= ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<uint> u_MaxSamples = ParameterKeys.NewValue<uint>();
    }
}
