// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering.SubsurfaceScattering
{
    public static partial class SubsurfaceScatteringBlurShaderKeys
    {
        public static readonly ValueParameterKey<Vector2> ProjectionSizeOnUnitPlaneInClipSpace = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> ScatteringWidths = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> IterationNumber = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Matrix> ViewProjectionMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ObjectParameterKey<Buffer> KernelBuffer = ParameterKeys.NewObject<Buffer>();
    }
}
