#if STRIDE_GRAPHICS_API_NULL 
//------------------------------------------------------------------------------
// <auto-generated>
//     Stride Effect Compiler File Generated:
//     Effect [SignedDistanceFieldFontShader]
//
//     Command Line: C:\work\Stash\Stride\sources\engine\Stride.Graphics\Shaders093.Bytecodes\..\..\..\..\Bin\Windows-Direct3D11\Stride.Core.Assets.CompilerApp.exe --profile=Windows-Null --platform=Windows --output-path=C:\work\Stash\Stride\sources\engine\Stride.Graphics\Shaders093.Bytecodes\obj\app_data --build-path=C:\work\Stash\Stride\sources\engine\Stride.Graphics\Shaders093.Bytecodes\obj\build_app_data --package-file=Graphics.sdpkg
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stride.Graphics 
{
    internal partial class SignedDistanceFieldFontShader
    {
        private static readonly byte[] signedDistanceFieldFontBytecode = new byte[] {
        };
    }
}

#endif
