// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using Stride.Graphics;
using Stride.Core.Mathematics;

namespace Stride.Rendering
{
    internal static partial class FogEffectKeys
    {
        public static readonly ValueParameterKey<Color3> FogColor = ParameterKeys.NewValue<Color3>(new Color3(1,1,1));
        public static readonly ValueParameterKey<float> Density = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> FogStart = ParameterKeys.NewValue<float>(0f);
        public static readonly ValueParameterKey<bool> skipBG = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<float> zFar = ParameterKeys.NewValue<float>(1000f);
        public static readonly ValueParameterKey<float> zNear = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ObjectParameterKey<Texture> DepthTexture = ParameterKeys.NewObject<Texture>();
    }
}
