(* := is an extension to define a literal with no whitespace between repeats and sequences *)
ws := {? Terminals.WhiteSpace ?};
eol := ? Terminals.Eol ?, {? Terminals.Eol ?};


letter_or_digit := ? Terminals.LetterOrDigit ?;

simple_value := letter_or_digit, {letter_or_digit};

bracket_value = simple value, {simple value};

expr := [eol], [ws], [eol];

block := "{", expr, "}";

first = optional_bracket;

second = optional_bracket;

grammar = ws, "shader", simple_value, block;