// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class CameraKeys
    {
        public static readonly ValueParameterKey<float> NearClipPlane = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> FarClipPlane = ParameterKeys.NewValue<float>(100.0f);
        public static readonly ValueParameterKey<Vector2> ZProjection = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> ViewSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> AspectRatio = ParameterKeys.NewValue<float>();
    }
}
