<Project>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildProjectDirectory), 'Directory.Build.props'))/sdk/Stride.Build.Sdk.Editor/Sdk/Sdk.props" />
  <PropertyGroup>
    <TargetFramework>$(StrideEditorTargetFramework)</TargetFramework>
    <StrideAssemblyProcessor>true</StrideAssemblyProcessor>
    <StrideAssemblyProcessorOptions>--serialization</StrideAssemblyProcessorOptions>
    <StridePackageKind>Editor</StridePackageKind>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\shared\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\editor\Stride.Assets.Presentation.Wpf\Stride.Assets.Presentation.Wpf.csproj" />
    <ProjectReference Include="..\Stride.Physics.Assets\Stride.Physics.Assets.csproj" />
    <ProjectReference Include="..\Stride.Physics\Stride.Physics.csproj" />
    <ProjectReference Include="..\Stride.Navigation\Stride.Navigation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\PhysicsComponent.png" />
    <EmbeddedResource Include="Resources\PhysicsConstraintComponent.png" />
  </ItemGroup>
  <Import Project="$(StrideRoot)sources/sdk/Stride.Build.Sdk.Editor/Sdk/Sdk.targets" />
</Project>
