// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering.Voxels
{
    internal static partial class ShaderMixins
    {
        internal partial class Voxel2x2x2MipmapEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "Voxel2x2x2Mipmap");
                if (context.GetParam(Voxel2x2x2MipmapKeys.mipmapper) != null)
                {

                    {
                        var __mixinToCompose__ = context.GetParam(Voxel2x2x2MipmapKeys.mipmapper);
                        var __subMixin = new ShaderMixinSource();
                        context.PushComposition(mixin, "mipmapper", __subMixin);
                        context.Mixin(__subMixin, __mixinToCompose__);
                        context.PopComposition();
                    }
                }
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("Voxel2x2x2MipmapEffect", new Voxel2x2x2MipmapEffect());
            }
        }
    }
}
