// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

using Xenko.Rendering.Lights;
namespace Xenko.Rendering.Voxels.VoxelGI
{
    public static partial class LightVoxelShaderKeys
    {
        public static readonly ValueParameterKey<float> Intensity = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> SpecularIntensity = ParameterKeys.NewValue<float>();
    }
}
