using CommunityToolkit.HighPerformance;
using CommunityToolkit.HighPerformance.Buffers;
using Stride.Shaders.Core;
using Stride.Shaders.Parsing;
using Stride.Shaders.Parsing.Analysis;
using Stride.Shaders.Parsing.SDSL;
using Stride.Shaders.Parsing.SDSL.AST;
using Stride.Shaders.Spirv.Core;
using Stride.Shaders.Spirv.Core.Buffers;
using Stride.Shaders.Spirv.Processing;
using Stride.Shaders.Spirv.Tools;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using Stride.Core.Storage;
using static Stride.Shaders.Spirv.Specification;
using Stride.Shaders.Spirv.Core.Parsing;
using System.Diagnostics.CodeAnalysis;

namespace Stride.Shaders.Spirv.Building;

public record class ShaderMixinInstantiation(List<ShaderClassInstantiation> Mixins, Dictionary<string, ShaderMixinInstantiation[]> Compositions);

public record struct ShaderBuffers(SpirvContext Context, SpirvBuffer Buffer)
{
    public static ShaderBuffers CreateFromSpan(Span<int> span)
    {
        if (span[0] != Specification.MagicNumber)
            throw new InvalidOperationException("SPIRV Magic number not found");

        var header = SpirvHeader.Read(span);

        var context = new SpirvContext();
        var buffer = new SpirvBuffer();

        int wid = SpirvHeader.IntSpanSize;
        bool isContext = true;
        while (wid < span.Length)
        {
            var instruction = new OpData(span.Slice(wid, span[wid] >> 16));
            if (instruction.Op == Op.OpShaderSDSL)
                isContext = false;
            (isContext ? context.GetBuffer() : buffer).Add(instruction);
            wid += span[wid] >> 16;
        }

        return new(context, buffer);
    }
}

public enum ResolveStep
{
    Compile,
    Mix,
}

public record class ShaderClassInstantiation(string ClassName, ConstantExpression[] GenericArguments, bool ImportStageOnly = false) : IEquatable<ShaderClassInstantiation>
{
    public ShaderBuffers? Buffer { get; set; }

    public string ClassName { get; set; } = ClassName;

    public ConstantExpression[] GenericArguments { get; set; } = GenericArguments;

    public ShaderDefinition? Symbol { get; set; }

    public string ToClassNameWithGenerics()
    {
        if ((GenericArguments == null || GenericArguments.Length == 0) && !ImportStageOnly)
            return ClassName;

        var result = new StringBuilder();
        result.Append(ClassName);
        if (GenericArguments != null && GenericArguments.Length > 0)
        {
            result.Append('<');
            result.Append(string.Join(",", GenericArguments.Select(x => x.ToString())));
            result.Append('>');
        }

        return result.ToString();
    }

    public override string ToString() => $"{(ImportStageOnly ? "stage " : string.Empty)}{ToClassNameWithGenerics()} Symbol: {Symbol} Buffer: {(Buffer != null ? "set" : "empty")}";

    public virtual bool Equals(ShaderClassInstantiation? shaderClassSource)
    {
        if (shaderClassSource is null) return false;
        if (ReferenceEquals(this, shaderClassSource)) return true;
        return
            string.Equals(ClassName, shaderClassSource.ClassName) &&
            GenericArguments.SequenceEqual(shaderClassSource.GenericArguments);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            int hashCode = ClassName?.GetHashCode() ?? 0;
            if (GenericArguments != null)
            {
                foreach (var current in GenericArguments)
                    hashCode = (hashCode * 397) ^ (current.GetHashCode());
            }

            return hashCode;
        }
    }
}

// Constant vector (generated by TryGetConstantValue)
public class ConstantVector
{
    public required object[] Values;

    public override string ToString()
    {
        var type = Values[0] switch
        {
            float => "float",
            _ => throw new NotSupportedException($"Unsupported constant vector element type: {Values[0].GetType()}"),
        };

        return $"{type}{Values.Length}({string.Join(",", Values)})";
    }
}


public partial class SpirvBuilder
{
    public static void BuildInheritanceListWithoutSelf(IExternalShaderLoader shaderLoader, SpirvContext topLevelContext, ShaderClassInstantiation classSource, ReadOnlySpan<ShaderMacro> macros, SpirvContext declaringContext, List<ShaderClassInstantiation> inheritanceList, ResolveStep resolveStep)
    {
        // Build shader name mapping and collect generic parameter expressions
        var shaderMapping = new Dictionary<int, ShaderClassInstantiation>();
        // Map generic parameter index → resolved expression from classSource
        ConstantExpression[]? resolvedGenericArgs = null;
        string? declaringClassName = null;
        // Also build import-level resolution: map shader name → its import's generic args (as expressions)
        // Used to resolve GenericParamExpr that reference parent shaders' generics
        var importArgsByName = new Dictionary<string, ConstantExpression[]>();

        foreach (var i in declaringContext)
        {
            if (i.Op == Op.OpGenericParameterSDSL && (OpGenericParameterSDSL)i is { } genericParameter)
            {
                if (genericParameter.Index >= classSource.GenericArguments.Length)
                    throw new NotImplementedException($"Not enough generic parameters specified when instantiating {classSource.ToClassNameWithGenerics()}");
                resolvedGenericArgs ??= classSource.GenericArguments;
                declaringClassName ??= genericParameter.DeclaringClass;
            }
            if (i.Op == Op.OpImportShaderSDSL && (OpImportShaderSDSL)i is { } importShader)
            {
                var shaderClassSource = ConvertToShaderClassSource(declaringContext, importShader);
                shaderMapping[importShader.ResultId] = shaderClassSource;
                if (shaderClassSource.GenericArguments.Length > 0)
                    importArgsByName[importShader.ShaderName] = shaderClassSource.GenericArguments;
            }
        }

        ConstantExpression ResolveGenericArg(ConstantExpression arg)
        {
            // First substitute the current shader's own generics
            if (resolvedGenericArgs != null && declaringClassName != null)
                arg = arg.Substitute(declaringClassName, resolvedGenericArgs);
            // Then resolve any remaining GenericParamExpr by looking up parent imports
            if (arg is GenericParamExpr genParam && importArgsByName.TryGetValue(genParam.DeclaringClass, out var parentArgs) && genParam.Index < parentArgs.Length)
                arg = ResolveGenericArg(parentArgs[genParam.Index]);
            return arg;
        }

        // Check inheritance
        foreach (var i in declaringContext)
        {
            if (i.Op == Op.OpMixinInheritSDSL && (OpMixinInheritSDSL)i is { } inherit)
            {
                if (!shaderMapping.TryGetValue(inherit.Shader, out var shaderName))
                {
                    throw new InvalidOperationException($"BuildInheritanceListWithoutSelf: OpMixinInheritSDSL references shader ID {inherit.Shader} not found in shaderMapping (shader: {classSource.ToClassNameWithGenerics()}, mapping keys: [{string.Join(", ", shaderMapping.Keys)}])");
                }

                // Resolve generic arguments: substitute own generics + resolve parent references
                if (shaderName.GenericArguments.Length > 0)
                {
                    var remappedArgs = new ConstantExpression[shaderName.GenericArguments.Length];
                    for (int index = 0; index < remappedArgs.Length; index++)
                        remappedArgs[index] = ResolveGenericArg(shaderName.GenericArguments[index]);
                    shaderName = shaderName with { GenericArguments = remappedArgs };
                }

                BuildInheritanceListIncludingSelf(shaderLoader, topLevelContext, shaderName, macros, inheritanceList, resolveStep);
            }
        }
    }

    public static ShaderClassInstantiation ConvertToShaderClassSource(SpirvContext declaringContext, OpImportShaderSDSL importShader)
    {
        var genericIds = importShader.Generics.Elements.Memory;
        var exprs = new ConstantExpression[genericIds.Length];
        for (int i = 0; i < genericIds.Length; i++)
            exprs[i] = ConstantExpression.ParseFromBuffer(genericIds.Span[i], declaringContext.GetBuffer(), declaringContext);
        return new ShaderClassInstantiation(importShader.ShaderName, exprs);
    }

    public static ShaderClassInstantiation BuildInheritanceListIncludingSelf(IExternalShaderLoader shaderLoader, SpirvContext context, ShaderClassInstantiation classSource, ReadOnlySpan<ShaderMacro> macros, List<ShaderClassInstantiation> inheritanceList, ResolveStep resolveStep)
    {
        // TODO: cache same instantiations within context?
        var index = inheritanceList.IndexOf(classSource);
        if (index == -1)
        {
            if (classSource.Buffer == null)
            {
                var shader = GetOrLoadShader(shaderLoader, classSource, macros, resolveStep, context);
                classSource.Buffer = shader;
            }

            // Note: since shader instantiation might mutate classSource, perform a search again
            index = inheritanceList.IndexOf(classSource);
            if (index == -1)
            {
                BuildInheritanceListWithoutSelf(shaderLoader, context, classSource, macros, classSource.Buffer.Value.Context, inheritanceList, resolveStep);
                index = inheritanceList.Count;
                inheritanceList.Add(classSource);
            }
        }

        return inheritanceList[index];
    }

    record struct GenericParameter(SymbolType Type, int ResultId, int ResultType, int Index, string Name, bool Resolved, string Value);

    abstract class GenericResolver
    {
        public abstract int GenericArgumentCount { get; }
        public virtual IShaderCache? Cache => null;

        public abstract string ResolveGenericAsString(int genericIndex);

        public abstract bool TryResolveGenericValue(SymbolType genericParameterType, string genericParameterName, int index, [MaybeNullWhen(false)] out object value);
        public abstract bool ResolveGenericValueInBuffer(SymbolType genericParameterType, string genericParameterName, int genericIndex, SpirvContext context, ref int instructionIndex, out string textValue);

        public virtual void ValidateGenericParameters(string classNameWithGenerics, List<GenericParameter> genericParameters)
        {
        }

        /// <summary>
        /// This will be executed in all cases for generic classes (even if generic instantiation was in the cache). 
        /// </summary>
        /// <param name="classNameWithGenerics"></param>
        public virtual void PostProcess(string classNameWithGenerics)
        {
        }
    }

    /// <summary>
    /// Instantiate generics using string values (they will be imported in the generic shader being specialized).
    /// </summary>
    class GenericResolverFromValues(string[] genericValues) : GenericResolver
    {
        public override int GenericArgumentCount => genericValues.Length;
        public override string ResolveGenericAsString(int genericIndex) => genericValues[genericIndex];

        public override bool TryResolveGenericValue(SymbolType genericParameterType, string genericParameterName, int index, out object value)
        {
            var genericValue = genericValues![index];
            switch (genericParameterType)
            {
                case ScalarType { Type: Scalar.Int }:
                    value = int.Parse(genericValue);
                    return true;
                case ScalarType { Type: Scalar.Float }:
                    value = float.Parse(genericValue);
                    return true;
                case ScalarType { Type: Scalar.Boolean }:
                    value = bool.Parse(genericValue);
                    return true;
                case GenericParameterType g:
                    value = genericValue;
                    return true;
                default:
                    throw new NotImplementedException();
            }
        }

        public override bool ResolveGenericValueInBuffer(SymbolType genericParameterType, string genericParameterName, int genericIndex, SpirvContext context, ref int instructionIndex, out string textValue)
        {
            var genericParameter = (OpGenericParameterSDSL)context[instructionIndex];
            var genericValue = genericValues![genericIndex];
            textValue = genericValue;
            switch (genericParameterType)
            {
                case ScalarType or VectorType:
                    var scanner = new Scanner(textValue);
                    ParseResult pr = new ParseResult();
                    if (!ExpressionParser.Expression(ref scanner, pr, out var expression))
                        throw new InvalidOperationException("Can't parse generic value");
                    var localContext = new SpirvContext();
                    var result = expression.CompileConstantValue(new SymbolTable(localContext, null!), localContext, genericParameterType);
                    context.RemoveAt(instructionIndex);
                    context.InsertWithoutDuplicates(ref instructionIndex, genericParameter.ResultId, localContext.GetBuffer());
                    return true;
                case GenericParameterType g:
                    context.Replace(instructionIndex++, new OpConstantStringSDSL(genericParameter.ResultId, genericValue));
                    return true;
                default:
                    throw new NotImplementedException();
            }
        }
    }

    /// <summary>
    /// Instantiate generics using another buffer for the shader constants. If a context is specified, constants will be imported there, otherwise inside the generic shader being instantiated.
    /// </summary>
    class GenericResolverFromInstantiatingBuffer(ShaderClassInstantiation classSource, ResolveStep resolveStep, SpirvContext declaringContext) : GenericResolver
    {
        public override int GenericArgumentCount => classSource.GenericArguments.Length;

        public override IShaderCache? Cache => declaringContext.GenericCache;

        public override string ResolveGenericAsString(int genericIndex)
        {
            var expr = classSource.GenericArguments[genericIndex];
            if (expr.TryEvaluate(out var constantValue) && constantValue is not null)
                return ShaderClassSource.ConvertGenericArgToString(constantValue);
            return expr.ToString();
        }

        public override bool TryResolveGenericValue(SymbolType genericParameterType, string genericParameterName, int index, out object value)
        {
            var expr = classSource.GenericArguments[index];
            if (expr.TryEvaluate(out var result) && result is not null)
            {
                value = result;
                return true;
            }

            value = expr.ToString();
            return false;
        }

        public override bool ResolveGenericValueInBuffer(SymbolType genericParameterType, string genericParameterName, int genericIndex, SpirvContext context, ref int instructionIndex, out string textValue)
        {
            textValue = ResolveGenericAsString(genericIndex);

            var genericParameter = (OpGenericParameterSDSL)context[instructionIndex];
            var expr = classSource.GenericArguments[genericIndex];

            // Build a standalone buffer from the expression, then import with the desired result ID.
            // This replaces the old extract-from-declaring-context + GenericParameter→GenericReference conversion.
            var constantBuffer = expr.EmitToBuffer();

            context.RemoveAt(instructionIndex);

            var bound = context.Bound;
            context.InsertWithoutDuplicates(ref instructionIndex, genericParameter.ResultId, constantBuffer);
            context.Bound = bound;

            return true;
        }

        public override void ValidateGenericParameters(string classNameWithGenerics, List<GenericParameter> genericParameters)
        {
            // Fully resolved?
            if (resolveStep == ResolveStep.Mix)
            {
                if (!genericParameters.All(x => x.Resolved))
                {
                    throw new InvalidOperationException("During mix phase, shaders generics are expected to be fully resolved");
                }
            }
        }

        public override void PostProcess(string classNameWithGenerics)
        {
            if (resolveStep == ResolveStep.Mix)
            {
                classSource.ClassName = classNameWithGenerics;
                classSource.GenericArguments = [];
            }
        }
    }

    private static void InstantiateGenericShader(ref ShaderBuffers shaderBuffers, string classNameWithGenerics, GenericResolver genericResolver, IExternalShaderLoader shaderLoader, ReadOnlySpan<ShaderMacro> macros)
    {
        var resolvedLinks = new Dictionary<int, string>();
        var semantics = new Dictionary<string, string>();

        var genericParameters = new List<GenericParameter>();
        string? currentShaderDeclaringClass = null;
        Dictionary<string, int[]>? importMap = null;
        for (int index = 0; index < shaderBuffers.Context.Count; ++index)
        {
            var i = shaderBuffers.Context[index];
            if (i.Op == Op.OpGenericParameterSDSL && (OpGenericParameterSDSL)i is { } genericParameter)
            {
                currentShaderDeclaringClass ??= genericParameter.DeclaringClass;
                var genericParameterType = shaderBuffers.Context.ReverseTypes[genericParameter.ResultType];
                var genericParameterName = shaderBuffers.Context.Names[genericParameter.ResultId];
                var instructionStart = index;
                var resolved = genericResolver.ResolveGenericValueInBuffer(genericParameterType, genericParameterName, genericParameters.Count, shaderBuffers.Context, ref index, out var textValue);
                genericParameters.Add(new(genericParameterType, genericParameter.ResultId, genericParameter.ResultType, i.Index, genericParameterName, resolved, textValue));

                // Process new types (if any)
                // Note: this might fail in case of types being reordered? (review that if it happens in more advanced cases)
                ShaderClass.ProcessNameAndTypes(shaderBuffers.Context, instructionStart, index);

                // Since we are positioned after the newly added instruction, adjust for it to consider next loop ++index
                index--;

                switch (genericParameterType)
                {
                    case GenericParameterType g when g.Kind is GenericParameterKindSDSL.LinkType:
                        resolvedLinks.Add(genericParameter.ResultId, textValue);
                        break;
                    case GenericParameterType g when g.Kind is GenericParameterKindSDSL.Semantic:
                        semantics.Add(shaderBuffers.Context.Names[genericParameter.ResultId], textValue);
                        break;
                }
            }

            // Resolve OpGenericReferenceSDSL by looking up the parent import's argument
            if (i.Op == Op.OpGenericReferenceSDSL)
            {
                // Build import map lazily (after all GenericParameters are resolved above)
                if (importMap == null)
                {
                    importMap = new();
                    foreach (var inst in shaderBuffers.Context)
                    {
                        if (inst.Op == Op.OpImportShaderSDSL && (OpImportShaderSDSL)inst is { } import)
                            importMap[import.ShaderName] = import.Generics.Elements.Memory.ToArray();
                    }
                    // Also map the current shader's own resolved generics, so references to
                    // the current shader's declaring class can be resolved.
                    if (currentShaderDeclaringClass != null && genericParameters.Count > 0)
                    {
                        var currentShaderArgs = new int[genericParameters.Count];
                        for (int j = 0; j < genericParameters.Count; j++)
                            currentShaderArgs[j] = genericParameters[j].ResultId;
                        importMap[currentShaderDeclaringClass] = currentShaderArgs;
                    }
                }

                // OpGenericReferenceSDSL has the same layout as OpGenericParameterSDSL
                var genRef = (OpGenericParameterSDSL)i;
                if (importMap.TryGetValue(genRef.DeclaringClass, out var args) && genRef.Index < args.Length)
                {
                    var resolvedArgId = args[genRef.Index];

                    // Follow transitive references: the resolved arg may itself be a GenericReference
                    // (e.g., ShadowMapReceiverBase refs → ShadowMapReceiverDirectional refs → concrete).
                    // Resolve the chain before extracting.
                    var visited = new HashSet<int>();
                    while (shaderBuffers.Context.GetBuffer().TryGetInstructionById(resolvedArgId, out var resolvedInst)
                           && (resolvedInst.Op == Op.OpGenericReferenceSDSL || resolvedInst.Op == Op.OpGenericParameterSDSL)
                           && visited.Add(resolvedArgId))
                    {
                        var innerRef = (OpGenericParameterSDSL)resolvedInst;
                        if (importMap.TryGetValue(innerRef.DeclaringClass, out var innerArgs) && innerRef.Index < innerArgs.Length)
                            resolvedArgId = innerArgs[innerRef.Index];
                        else
                            break; // Can't resolve further
                    }

                    // Extract the resolved constant and its dependencies from the context buffer
                    var constantBuffer = SpirvContext.ExtractConstantFromBuffer(resolvedArgId, shaderBuffers.Context.GetBuffer());
                    // Remove the GenericReference and insert the resolved constant with the same ResultId
                    shaderBuffers.Context.RemoveAt(index);
                    shaderBuffers.Context.InsertWithoutDuplicates(ref index, genRef.ResultId, constantBuffer);
                    index--; // adjust for loop increment
                }
            }

            if (i.Op == Op.OpTypeArray && (OpTypeArray)i is { } typeArray)
            {
                // Make sure constant is a proper OpConstant (i.e. not an OpSpecConstant/OpSpecConstantOp)
                if (!shaderBuffers.Context.GetBuffer().TryGetInstructionById(typeArray.Length, out var lengthInstruction))
                    throw new InvalidOperationException();
                if (lengthInstruction.Op != Op.OpConstant)
                {
                    var expr = ConstantExpression.ParseFromBuffer(typeArray.Length, shaderBuffers.Context.GetBuffer(), shaderBuffers.Context);
                    if (expr.TryEvaluate(out var value) && value != null)
                    {
                        var resultType = lengthInstruction.Data.IdResultType!.Value;
                        var resultId = lengthInstruction.Data.IdResult!.Value;
                        if (value is int or long)
                            shaderBuffers.Context.Replace(lengthInstruction.Index, new OpConstant<int>(resultType, resultId, System.Convert.ToInt32(value)));
                        else if (value is float or double)
                            shaderBuffers.Context.Replace(lengthInstruction.Index, new OpConstant<float>(resultType, resultId, System.Convert.ToSingle(value)));
                    }
                }
            }
        }

        //Console.WriteLine($"[Shader] Instantiating {classNameWithGenerics}");

        foreach (var i in shaderBuffers.Buffer)
        {
            if (i.Op == Op.OpShaderSDSL && (OpShaderSDSL)i is { } shaderDeclaration)
                shaderDeclaration.ShaderName = classNameWithGenerics;
        }

        TransformResolvedSemantics(shaderBuffers.Context, semantics);
        TransformResolvedLinkIdIntoLinkString(shaderBuffers.Context, resolvedLinks);

        genericResolver.ValidateGenericParameters(classNameWithGenerics, genericParameters);
    }

    private static string BuildGenericArguments(GenericResolver resolver)
    {
        var result = new string[resolver.GenericArgumentCount];
        for (int i = 0; i < resolver.GenericArgumentCount; i++)
            result[i] = resolver.ResolveGenericAsString(i);
        return string.Join(',', result);
    }

    private static string BuildGenericClassName(string className, string genericArguments)
    {
        StringBuilder sb = new();
        sb.Append(className)
            .Append("<")
            .Append(genericArguments)
            .Append(">");
        return sb.ToString();
    }

    private static void TransformResolvedSemantics(SpirvContext context, Dictionary<string, string> semantics)
    {
        foreach (var i in context)
        {
            if (i.Op == Op.OpDecorateString && (OpDecorateString)i is { Decoration: Decoration.UserSemantic, Value: string m } decorate)
            {
                if (semantics.TryGetValue(m, out var newSemantic))
                    decorate.Value = newSemantic;
            }
            else if (i.Op == Op.OpMemberDecorateString && (OpMemberDecorateString)i is { Decoration: Decoration.UserSemantic, Value: string m2 } decorate2)
            {
                if (semantics.TryGetValue(m2, out var newSemantic))
                    decorate2.Value = newSemantic;
            }
        }
    }

    private static void InstantiateMemberNames(ref ShaderBuffers shaderBuffers, string shaderName, GenericResolver genericResolver, IExternalShaderLoader shaderLoader, ReadOnlySpan<ShaderMacro> macros)
    {
        bool hasUnresolvableShader = false;
        for (var index = 0; index < shaderBuffers.Buffer.Count; index++)
        {
            var i = shaderBuffers.Buffer[index];
            if (i.Op == Op.OpUnresolvableShaderSDSL && (OpUnresolvableShaderSDSL)i is { } unresolvableShader)
            {
                hasUnresolvableShader = true;
            }
        }

        if (!hasUnresolvableShader)
            return;

        // Extract original filename from context (for debug info in recompiled shader)
        string? originalFilename = null;
        foreach (var i in shaderBuffers.Context)
        {
            if (i.Op == Specification.Op.OpString)
            {
                originalFilename = ((OpString)i).Value;
                break;
            }
        }

        var instantiatedGenericsMacros = new List<(string Name, string Definition)>();
        var genericParameterIndex = 0;
        foreach (var i in shaderBuffers.Context)
        {
            if (i.Op == Op.OpGenericParameterSDSL && (OpGenericParameterSDSL)i is { } genericParameter)
            {
                var genericParameterName = shaderBuffers.Context.Names[genericParameter.ResultId];
                var genericParameterType = shaderBuffers.Context.ReverseTypes[genericParameter.ResultType];
                if (genericParameterType is GenericParameterType { Kind: GenericParameterKindSDSL.MemberName })
                {
                    if (genericResolver.TryResolveGenericValue(genericParameterType, genericParameterName, genericParameterIndex, out var value))
                        instantiatedGenericsMacros.Add((shaderBuffers.Context.Names[genericParameter], value.ToString()!));
                }
                genericParameterIndex++;
            }
        }
        foreach (var i in shaderBuffers.Buffer)
        {
            if (i.Op == Op.OpUnresolvableShaderSDSL && (OpUnresolvableShaderSDSL)i is { } unresolvableShader)
            {
                var code = unresolvableShader.ShaderCode;
                if (instantiatedGenericsMacros.Count > 0)
                {
                    var cacheKey = shaderName + $"_{string.Join("_", instantiatedGenericsMacros.Select(x => RemoveInvalidCharactersFromSymbol(x.Definition)))}";

                    // Apply the preprocessor only to the shader body to substitute MemberName values
                    // without touching the generic definition
                    code = code.Substring(0, unresolvableShader.ShaderCodeNameEnd)
                                .Replace("MemberName ", "MemberNameResolved ")
                        + MonoGamePreProcessor.Run(code.Substring(unresolvableShader.ShaderCodeNameEnd), $"{shaderName}.sdsl", CollectionsMarshal.AsSpan(instantiatedGenericsMacros));

                    shaderName = cacheKey;
                }

                // Use original filename for debug info (OpString/OpSource) but skip OpSourceHashSDSL
                // since the hash would be of the macro-expanded code, not the original file
                shaderLoader.SuppressSourceHash = true;
                if (!shaderLoader.LoadExternalBuffer(shaderName, originalFilename, code, macros, out shaderBuffers, out var compiledHash, out _))
                    throw new InvalidOperationException();

                // Register under the MemberName cache key (e.g. "Foo_PerMaterial")
                shaderLoader.Cache.RegisterShader(shaderName, null, macros, shaderBuffers, compiledHash);
            }
        }
    }

    private static void TransformResolvedLinkIdIntoLinkString(SpirvContext context, Dictionary<int, string> resolvedLinks)
    {
        // Try to resolve LinkType generics
        for (var index = 0; index < context.Count; index++)
        {
            var i = context[index];
            if (i.Op == Op.OpDecorate && ((OpDecorate)i) is { Decoration: Decoration.LinkIdSDSL, DecorationParameters: { } m } linkDecorate)
            {
                var n = m.To<DecorationParams.LinkIdSDSL>();
                if (resolvedLinks.TryGetValue(n.IdRef0, out var resolvedValue))
                {
                    context.Replace(index, new OpDecorateString(linkDecorate.Target, Decoration.LinkSDSL, resolvedValue));
                }
            }
            else if (i.Op == Op.OpMemberDecorate && ((OpMemberDecorate)i) is { Decoration: Decoration.LinkIdSDSL, DecorationParameters: { } m2 } linkDecorate2)
            {
                var tmp = new OpMemberDecorate(i);
                var n = m2.To<DecorationParams.LinkIdSDSL>();
                if (resolvedLinks.TryGetValue(n.IdRef0, out var resolvedValue))
                {
                    context.Replace(index, new OpMemberDecorateString(linkDecorate2.StructureType, linkDecorate2.Member, Decoration.LinkSDSL, resolvedValue));
                }
            }
        }
    }

    public static void SetOpNop(Span<int> words)
    {
        words[0] = words.Length << 16;
        words[1..].Clear();
    }

    public static bool ContainIds(HashSet<int> ids, OpData i)
    {
        foreach (var op in i)
        {
            if (op.Kind == OperandKind.IdRef
                 || op.Kind == OperandKind.IdResult
                 || op.Kind == OperandKind.IdResultType
                 || op.Kind == OperandKind.IdScope
                 || op.Kind == OperandKind.IdMemorySemantics
                 || op.Kind == OperandKind.PairIdRefIdRef)
            {
                foreach (var word in op.Words)
                    if (ids.Contains(word))
                        return true;
            }
            else if (op.Kind == OperandKind.PairIdRefLiteralInteger)
            {
                for (int j = 0; j < op.Words.Length; j += 2)
                    if (ids.Contains(op.Words[j]))
                        return true;
            }
            else if (op.Kind == OperandKind.PairLiteralIntegerIdRef)
            {
                for (int j = 1; j < op.Words.Length; j += 2)
                    if (ids.Contains(op.Words[j]))
                        return true;
            }
        }

        return false;
    }

    public static void RemapIds(SpirvBuffer buffer, int shaderStart, int shaderEnd, Dictionary<int, int> idRemapping)
    {
        if (idRemapping.Count == 0)
            return;
        for (var index = shaderStart; index < buffer.Count; index++)
        {
            var i = buffer[index];
            RemapIds(idRemapping, ref i.Data);
        }
    }

    public static void RemapIds(Dictionary<int, int> idRemapping, ref OpData i)
    {
        if (idRemapping.Count == 0)
            return;
        // Special case: remove OpName and such
        if (i.Op == Op.OpName || i.Op == Op.OpDecorate || i.Op == Op.OpDecorateString
            || i.Op == Op.OpMemberName || i.Op == Op.OpMemberDecorate || i.Op == Op.OpMemberDecorateString)
        {
            // Target/Structure ID is always stored in first operand for all those instructions
            var target = i.Memory.Span[1];
            if (idRemapping.ContainsKey(target))
                SetOpNop(i.Memory.Span);
            return;
        }

        foreach (var op in i)
        {
            if (op.Kind == OperandKind.IdRef
                 || op.Kind == OperandKind.IdResult
                 || op.Kind == OperandKind.IdResultType
                 || op.Kind == OperandKind.IdScope
                 || op.Kind == OperandKind.IdMemorySemantics
                 || op.Kind == OperandKind.PairIdRefIdRef)
            {
                foreach (ref var word in op.Words)
                {
                    if (idRemapping.TryGetValue(word, out var to1))
                        word = to1;
                }

                // Special case: remove duplicates in OpEntryPoint
                if (i.Op == Op.OpEntryPoint && op.Quantifier == OperandQuantifier.ZeroOrMore)
                {
                    var entryPoint = new OpEntryPoint(ref i);

                    var existing = new HashSet<int>();
                    var target = 0;
                    for (int index = 0; index < entryPoint.InterfaceIds.Elements.Length; ++index)
                    {
                        if (existing.Add(entryPoint.InterfaceIds.Elements.Span[index]))
                        {
                            entryPoint.InterfaceIds.Elements.Span[target++] = entryPoint.InterfaceIds.Elements.Span[index];
                        }
                    }

                    // Slice and reassign to refresh InstructionMemory and size
                    entryPoint.InterfaceIds = entryPoint.InterfaceIds.Slice(0, target);
                }
            }

            if (op.Kind == OperandKind.PairIdRefLiteralInteger)
            {
                for (int j = 0; j < op.Words.Length; j += 2)
                {
                    if (idRemapping.TryGetValue(op.Words[j], out var to2))
                        op.Words[j] = to2;
                }
            }

            if (op.Kind == OperandKind.PairLiteralIntegerIdRef)
            {
                for (int j = 1; j < op.Words.Length; j += 2)
                {
                    if (idRemapping.TryGetValue(op.Words[j], out var to2))
                        op.Words[j] = to2;
                }
            }
        }
    }

    public static void CollectIds(OpData i, Action<int> ids)
    {
        foreach (var op in i)
        {
            if (op.Kind == OperandKind.IdRef
                || op.Kind == OperandKind.IdResult
                || op.Kind == OperandKind.IdResultType
                || op.Kind == OperandKind.IdScope
                || op.Kind == OperandKind.IdMemorySemantics
                || op.Kind == OperandKind.PairIdRefIdRef)
            {
                foreach (var word in op.Words)
                    ids(word);
            }
            else if (op.Kind == OperandKind.PairIdRefLiteralInteger)
            {
                for (int j = 0; j < op.Words.Length; j += 2)
                    ids(op.Words[j]);
            }
            else if (op.Kind == OperandKind.PairLiteralIntegerIdRef)
            {
                for (int j = 1; j < op.Words.Length; j += 2)
                    ids(op.Words[j]);
            }
        }
    }

    /// <summary>
    /// Gets or load a shader, with generic instantiation (if requested).
    /// </summary>
    /// <param name="shaderLoader"></param>
    /// <param name="classSource">The generics parameters should be in <see cref="parentBuffer"/>.</param>
    /// <param name="macros"></param>
    /// <param name="resolveStep"></param>
    /// <returns></returns>
    /// <param name="parentBuffer"></param>
    public static ShaderBuffers GetOrLoadShader(IExternalShaderLoader shaderLoader, ShaderClassInstantiation classSource, ReadOnlySpan<ShaderMacro> macros, ResolveStep resolveStep, SpirvContext context)
    {
        if (resolveStep == ResolveStep.Mix && classSource.GenericArguments.Length > 0)
        {
            // At mix time, generics are fully resolved — resolve to string values
            // and use the value-based path which caches to shaderLoader.Cache (persistent)
            var genericValues = new string[classSource.GenericArguments.Length];
            for (int i = 0; i < genericValues.Length; i++)
            {
                var expr = classSource.GenericArguments[i];
                if (expr.TryEvaluate(out var constantValue) && constantValue is not null)
                    genericValues[i] = ShaderClassSource.ConvertGenericArgToString(constantValue);
                else
                    throw new InvalidOperationException($"Generic argument {i} ({expr}) for {classSource.ClassName} could not be resolved during mix phase");
            }

            var result = GetOrLoadShader(shaderLoader, classSource.ClassName, genericValues, macros);

            // PostProcess: update classSource (same as GenericResolverFromInstantiatingBuffer.PostProcess)
            var classNameWithGenerics = $"{classSource.ClassName}<{string.Join(",", genericValues)}>";
            classSource.ClassName = classNameWithGenerics;
            classSource.GenericArguments = [];

            return result;
        }

        return GetOrLoadShader(shaderLoader, classSource.ClassName, new GenericResolverFromInstantiatingBuffer(classSource, resolveStep, context), macros);
    }

    public static ShaderBuffers GetOrLoadShader(IExternalShaderLoader shaderLoader, string className, string[]? genericValues, ReadOnlySpan<ShaderMacro> macros)
    {
        if (genericValues is null)
            return GetOrLoadShader(shaderLoader, className, macros, out var hash, out var isFromCache);

        return GetOrLoadShader(shaderLoader, className, new GenericResolverFromValues(genericValues), macros);
    }

    private static ShaderBuffers GetOrLoadShader(IExternalShaderLoader shaderLoader, string className, GenericResolver genericResolver, ReadOnlySpan<ShaderMacro> macros)
    {
        var shaderBuffers = GetOrLoadShader(shaderLoader, className, macros, out var hash, out var isFromCache);

        if (genericResolver.GenericArgumentCount > 0)
        {
            // First, try to build name for cache lookup
            var genericArguments = BuildGenericArguments(genericResolver);
            var classNameWithGenerics = BuildGenericClassName(className, genericArguments);
            var cache = genericResolver.Cache ?? shaderLoader.Cache;
            if (cache.TryLoadFromCache(className, genericArguments, macros, out var cachedShaderBuffers, out var cachedHash))
            {
                shaderBuffers = cachedShaderBuffers;
                hash = cachedHash;
            }
            else
            {
                var macrosArray = macros.ToArray();
                var localShaderBuffers = shaderBuffers;
                var localHash = hash;
                var result = shaderLoader.GenericCache.GetOrInstantiate(className, genericArguments, macros, () =>
                {
                    // Double-check cache
                    if (cache.TryLoadFromCache(className, genericArguments, macrosArray, out var buf, out var h))
                        return (buf, h);

                    var localBuffers = localShaderBuffers;
                    InstantiateMemberNames(ref localBuffers, className, genericResolver, shaderLoader, macrosArray);

                    // Copy buffers (we don't want to edit original non-instantiated code as it might be reloaded through caching)
                    localBuffers.Context = new SpirvContext(CopyBuffer(localBuffers.Context.GetBuffer()))
                    {
                        Bound = localBuffers.Context.Bound,
                        Names = new(localBuffers.Context.Names),
                        Types = new(localBuffers.Context.Types),
                        ReverseTypes = new(localBuffers.Context.ReverseTypes),
                    };
                    localBuffers.Buffer = CopyBuffer(localBuffers.Buffer);

                    InstantiateGenericShader(ref localBuffers, classNameWithGenerics, genericResolver, shaderLoader, macrosArray);

                    cache.RegisterShader(className, genericArguments, macrosArray, localBuffers, localHash);
                    return (localBuffers, localHash);
                });

                shaderBuffers = result.Buffer;
                hash = result.Hash;
            }

            // Run in all cases (even if cached)
            genericResolver.PostProcess(classNameWithGenerics);
        }

        return shaderBuffers;
    }

    public static SpirvBuffer CopyBuffer(SpirvBuffer shader)
    {
        var copiedShader = new SpirvBuffer();
        foreach (var i in shader)
        {
            var i2 = new OpData(i.Data.Memory.Span);
            copiedShader.Add(i2);
        }
        shader = copiedShader;
        return shader;
    }

    public static List<int> CollectGenerics(SpirvBuffer shader)
    {
        // Collect OpGenericParameterSDSL
        List<int> generics = new();
        for (var index = 0; index < shader.Count; index++)
        {
            var i = shader[index];
            if (i.Op == Op.OpGenericParameterSDSL && (OpGenericParameterSDSL)i is { } genericParameter)
            {
                generics.Add(genericParameter.ResultId);
                SetOpNop(i.Data.Memory.Span);
            }
        }

        return generics;
    }

    public static ShaderBuffers GetOrLoadShader(IExternalShaderLoader shaderLoader, string className, ReadOnlySpan<ShaderMacro> defines, out ObjectId hash, out bool isFromCache)
    {
        //Console.WriteLine($"[Shader] Requesting non-generic class {className}");

        if (!shaderLoader.LoadExternalBuffer(className, defines, out var buffer, out hash, out isFromCache))
            throw new InvalidOperationException($"Could not load shader [{className}]");

        //if (!isFromCache)
        //    Console.WriteLine($"[Shader] Loading non-generic class {className} for 1st time");

        return buffer;
    }
}
