// Copyright (c) Stride contributors (https://stride3d.net) and Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.
namespace Stride.Core.Shaders.Grammar
{
    /// <summary>
    /// Token type.
    /// </summary>
    public enum TokenType
    {
        Eof = 0,
        Error = 1,
        Whitespace = 2,
        CommentEnd = 3,
        SingleLineComment = 4,
        MultiLineComment = 5,
        AddAssign = 6,
        And = 7,
        Arrobas = 8,
        Assign = 9,
        BitwiseAnd = 10,
        BitwiseAndAssign = 11,
        BitwiseNot = 12,
        BitwiseOr = 13,
        BitwiseOrAssign = 14,
        BitwiseShiftLeft = 15,
        BitwiseShiftLeftAssign = 16,
        BitwiseShiftRight = 17,
        BitwiseShiftRightAssign = 18,
        BitwiseXor = 19,
        BitwiseXorAssign = 20,
        Colon = 21,
        Comma = 22,
        Div = 23,
        DivAssign = 24,
        Dot = 25,
        Equal = 26,
        FloatingPointLiteral = 27,
        FloatingPointLiteralExponent = 28,
        GreaterThan = 29,
        GreaterThanOrEqual = 30,
        HexEscapeCharLiteral = 31,
        HexIntegerLiteral = 32,
        Identifier = 33,
        IdentifierSeparator = 34,
        IndirectCharLiteral = 35,
        LeftBracket = 36,
        LeftCurly = 37,
        LeftParen = 38,
        LessThan = 39,
        LessThanOrEqual = 40,
        LineContinuation = 41,
        Minus = 42,
        MinusMinus = 43,
        Mod = 44,
        ModAssign = 45,
        Mul = 46,
        MulAssign = 47,
        NewLine = 48,
        Not = 49,
        NotEqual = 50,
        OctalEscapeCharLiteral = 51,
        OctalIntegerLiteral = 52,
        Or = 53,
        Plus = 54,
        PlusPlus = 55,
        Preprocessor = 56,
        Question = 57,
        RightBracket = 58,
        RightCurly = 59,
        RightParen = 60,
        Semi = 61,
        StandardEscapeCharLiteral = 62,
        StartWithNoZeroDecimalIntegerLiteral = 63,
        StartWithZeroDecimalIntegerLiteral = 64,
        StringLiteral = 65,
        SubAssign = 66,
        TokenPasting = 67,
        WS = 68,
        Unknown = 69,
    }
}
