// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering.Voxels
{
    public static partial class ClearBufferKeys
    {
        public static readonly ObjectParameterKey<Buffer> buffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ValueParameterKey<int> offset = ParameterKeys.NewValue<int>();
    }
}
