//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stride.LauncherApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stride.LauncherApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you do not have any version of Stride currently installed. Would you like to install the latest version?.
        /// </summary>
        public static string AskInstallVersion {
            get {
                return ResourceManager.GetString("AskInstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to install the latest version of the Visual Studio integration? This is highly recommended for programmers!.
        /// </summary>
        public static string AskInstallVSIX {
            get {
                return ResourceManager.GetString("AskInstallVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve Stride! We are making an online survey that takes about 5 minutes to complete. Would you like to answer it?.
        /// </summary>
        public static string AskSurvey {
            get {
                return ResourceManager.GetString("AskSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the launcher after starting Stride.
        /// </summary>
        public static string AutoCloseLauncher {
            get {
                return ResourceManager.GetString("AutoCloseLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        public static string ButtonAnswers {
            get {
                return ResourceManager.GetString("ButtonAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with us.
        /// </summary>
        public static string ButtonDiscord {
            get {
                return ResourceManager.GetString("ButtonDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discuss about Stride.
        /// </summary>
        public static string ButtonForums {
            get {
                return ResourceManager.GetString("ButtonForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork on GitHub.
        /// </summary>
        public static string ButtonGithub {
            get {
                return ResourceManager.GetString("ButtonGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        public static string ButtonIssues {
            get {
                return ResourceManager.GetString("ButtonIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the roadmap.
        /// </summary>
        public static string ButtonRoadmap {
            get {
                return ResourceManager.GetString("ButtonRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show us your work.
        /// </summary>
        public static string ButtonShowcase {
            get {
                return ResourceManager.GetString("ButtonShowcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer the survey.
        /// </summary>
        public static string ButtonSurvey {
            get {
                return ResourceManager.GetString("ButtonSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to uninstall version {0}?.
        /// </summary>
        public static string ConfirmUninstall {
            get {
                return ResourceManager.GetString("ConfirmUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details:.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading release notes….
        /// </summary>
        public static string DownloadingReleaseNotes {
            get {
                return ResourceManager.GetString("DownloadingReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to process a developer version: {0}.
        /// </summary>
        public static string ErrorDevRedirect {
            get {
                return ResourceManager.GetString("ErrorDevRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the version {0}. This project cannot be open..
        /// </summary>
        public static string ErrorDoNotFindVersion {
            get {
                return ResourceManager.GetString("ErrorDoNotFindVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing version {0}..
        /// </summary>
        public static string ErrorInstallingVersion {
            get {
                return ResourceManager.GetString("ErrorInstallingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing Visual Studio plugin..
        /// </summary>
        public static string ErrorInstallingVSIX {
            get {
                return ResourceManager.GetString("ErrorInstallingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Stride server. Switching to offline mode….
        /// </summary>
        public static string ErrorOfflineMode {
            get {
                return ResourceManager.GetString("ErrorOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to open a web browser.
        /// </summary>
        public static string ErrorOpeningBrowser {
            get {
                return ResourceManager.GetString("ErrorOpeningBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to start the program: {0}.
        /// </summary>
        public static string ErrorStartingProcess {
            get {
                return ResourceManager.GetString("ErrorStartingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uninstalling version {0}..
        /// </summary>
        public static string ErrorUninstallingVersion {
            get {
                return ResourceManager.GetString("ErrorUninstallingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uninstalling Visual Studio plugin..
        /// </summary>
        public static string ErrorUninstallingVSIX {
            get {
                return ResourceManager.GetString("ErrorUninstallingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version {0} is being updated. Please wait a moment..
        /// </summary>
        public static string ErrorVersionBeingUpdated {
            get {
                return ResourceManager.GetString("ErrorVersionBeingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version {0} is not currently installed. Do you want to install it now?.
        /// </summary>
        public static string ErrorVersionNotInstalled {
            get {
                return ResourceManager.GetString("ErrorVersionNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of this version is already in progress. Please wait a moment..
        /// </summary>
        public static string InstallAlreadyInProgress {
            get {
                return ResourceManager.GetString("InstallAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install latest version.
        /// </summary>
        public static string InstallLatestVersion {
            get {
                return ResourceManager.GetString("InstallLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install {0}.
        /// </summary>
        public static string InstallVersion {
            get {
                return ResourceManager.GetString("InstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stride launcher.
        /// </summary>
        public static string LauncherTitle {
            get {
                return ResourceManager.GetString("LauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on {0:d MMM yyyy}.
        /// </summary>
        public static string NewsDate {
            get {
                return ResourceManager.GetString("NewsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher needs to be updated download or installation failed due to the following reason:
        ///
        ///{0}
        ///
        ///Please go to Stride website and download a new version..
        /// </summary>
        public static string NewVersionDownloadError {
            get {
                return ResourceManager.GetString("NewVersionDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch documentation.
        /// </summary>
        public static string NoDocumentation {
            get {
                return ResourceManager.GetString("NoDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch news feed.
        /// </summary>
        public static string NoNews {
            get {
                return ResourceManager.GetString("NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project created yet!.
        /// </summary>
        public static string NoProjectCreated {
            get {
                return ResourceManager.GetString("NoProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download release notes.
        /// </summary>
        public static string NoReleaseNotes {
            get {
                return ResourceManager.GetString("NoReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version currently installed.
        /// </summary>
        public static string NoVersionInstalled {
            get {
                return ResourceManager.GetString("NoVersionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with {0}.
        /// </summary>
        public static string OpenProjectWithVersion {
            get {
                return ResourceManager.GetString("OpenProjectWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From List.
        /// </summary>
        public static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking….
        /// </summary>
        public static string ReportChecking {
            get {
                return ResourceManager.GetString("ReportChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}….
        /// </summary>
        public static string ReportDeletingVersion {
            get {
                return ResourceManager.GetString("ReportDeletingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering….
        /// </summary>
        public static string ReportDiscovering {
            get {
                return ResourceManager.GetString("ReportDiscovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}… ({1}%).
        /// </summary>
        public static string ReportDownloadingVersion {
            get {
                return ResourceManager.GetString("ReportDownloadingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Visual Studio plugin… ({0}%).
        /// </summary>
        public static string ReportDownloadingVSIX {
            get {
                return ResourceManager.GetString("ReportDownloadingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing prerequisites….
        /// </summary>
        public static string ReportInstallingPrerequisites {
            get {
                return ResourceManager.GetString("ReportInstallingPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}….
        /// </summary>
        public static string ReportInstallingVersion {
            get {
                return ResourceManager.GetString("ReportInstallingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Visual Studio plugin….
        /// </summary>
        public static string ReportInstallingVSIX {
            get {
                return ResourceManager.GetString("ReportInstallingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing plugin for {0}….
        /// </summary>
        public static string ReportVSIXInstallForVersion {
            get {
                return ResourceManager.GetString("ReportVSIXInstallForVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SelfUpdateExit {
            get {
                return ResourceManager.GetString("SelfUpdateExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the launcher is being downloaded….
        /// </summary>
        public static string SelfUpdateMessage {
            get {
                return ResourceManager.GetString("SelfUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating….
        /// </summary>
        public static string SelfUpdateTitle {
            get {
                return ResourceManager.GetString("SelfUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Explorer.
        /// </summary>
        public static string ShowInExplorer {
            get {
                return ResourceManager.GetString("ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start {0}.
        /// </summary>
        public static string StartVersion {
            get {
                return ResourceManager.GetString("StartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch/update version.
        /// </summary>
        public static string SwitchOrUpdateVersion {
            get {
                return ResourceManager.GetString("SwitchOrUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string TabGettingStarted {
            get {
                return ResourceManager.GetString("TabGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string TabNews {
            get {
                return ResourceManager.GetString("TabNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to hide beta versions.
        /// </summary>
        public static string ToggleHideBetaVersions {
            get {
                return ResourceManager.GetString("ToggleHideBetaVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to show beta versions.
        /// </summary>
        public static string ToggleShowBetaVersions {
            get {
                return ResourceManager.GetString("ToggleShowBetaVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ToolTipDefault {
            get {
                return ResourceManager.GetString("ToolTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install version {0}.
        /// </summary>
        public static string ToolTipDownload {
            get {
                return ResourceManager.GetString("ToolTipDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the latest available version of Stride.
        /// </summary>
        public static string ToolTipInstallLatestVersion {
            get {
                return ResourceManager.GetString("ToolTipInstallLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this project with a more recent version of Stride (the project will be upgraded).
        /// </summary>
        public static string ToolTipOpenAndUpgradeProject {
            get {
                return ResourceManager.GetString("ToolTipOpenAndUpgradeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &apos;{0}&apos;.
        /// </summary>
        public static string ToolTipOpenLink {
            get {
                return ResourceManager.GetString("ToolTipOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set current version to {0}.
        /// </summary>
        public static string ToolTipSetActiveVersion {
            get {
                return ResourceManager.GetString("ToolTipSetActiveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Stride Game Studio {0}.
        /// </summary>
        public static string ToolTipStartButton {
            get {
                return ResourceManager.GetString("ToolTipStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall version {0}.
        /// </summary>
        public static string ToolTipUninstall {
            get {
                return ResourceManager.GetString("ToolTipUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and update to version {0}.
        /// </summary>
        public static string ToolTipUpdate {
            get {
                return ResourceManager.GetString("ToolTipUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Visual Studio plugin.
        /// </summary>
        public static string ToolTipVisualStudioPlugin {
            get {
                return ResourceManager.GetString("ToolTipVisualStudioPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown version.
        /// </summary>
        public static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string VersionButton {
            get {
                return ResourceManager.GetString("VersionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not installed).
        /// </summary>
        public static string VersionButtonUninstalled {
            get {
                return ResourceManager.GetString("VersionButtonUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (update available).
        /// </summary>
        public static string VersionButtonUpdateAvailable {
            get {
                return ResourceManager.GetString("VersionButtonUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio plugin.
        /// </summary>
        public static string VisualStudioPlugin {
            get {
                return ResourceManager.GetString("VisualStudioPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has occurred during the installation of Visual Studio plugin. Check that you have at least one of the compatible version of Visual Studio installed (2012, 2013 or 2015)..
        /// </summary>
        public static string VSIXInstallFailed {
            get {
                return ResourceManager.GetString("VSIXInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio plugin has been successfully installed. Please restart running instances of Visual Studio..
        /// </summary>
        public static string VSIXInstallSucessful {
            get {
                return ResourceManager.GetString("VSIXInstallSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string VSIXVerbInstall {
            get {
                return ResourceManager.GetString("VSIXVerbInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string VSIXVerbReinstall {
            get {
                return ResourceManager.GetString("VSIXVerbReinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string VSIXVerbUpdate {
            get {
                return ResourceManager.GetString("VSIXVerbUpdate", resourceCulture);
            }
        }
    }
}
