// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class TestComputeShaderKeys
    {
        public static readonly ValueParameterKey<Vector3> ThreadGroupCountGlobal = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<uint> ParticleCount = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> ParticleStartIndex = ParameterKeys.NewValue<uint>();
        public static readonly ObjectParameterKey<Buffer> ParticleSortBuffer = ParameterKeys.NewObject<Buffer>();
    }
}
