// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering.Shadows
{
    internal static partial class ShadowMapReceiverBaseKeys
    {
        public static readonly ValueParameterKey<Matrix> WorldToShadowCascadeUV = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> InverseWorldToShadowCascadeUV = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> ViewMatrices = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector2> DepthRanges = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> DepthBiases = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> OffsetScales = ParameterKeys.NewValue<float>();
    }
}
