// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class VoxelStorageTextureClipmapShaderKeys
    {
        public static readonly ValueParameterKey<Vector4> perMapOffsetScale = ParameterKeys.NewValue<Vector4>();
        public static readonly ObjectParameterKey<Texture> clipMaps = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> mipMaps = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> LinearBorderSampler3D = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> LinearBorderSampler3D_NearestMip = ParameterKeys.NewObject<SamplerState>();
    }
}
