// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering.Voxels
{
    internal static partial class ShaderMixins
    {
        internal partial class BufferToTextureColumnsEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "BufferToTextureColumns");
                if (context.GetParam(BufferToTextureKeys.AttributesIndirect) != null)
                {
                    foreach(var attr in context.GetParam(BufferToTextureKeys.AttributesIndirect))

                    {

                        {
                            var __mixinToCompose__ = (attr);
                            var __subMixin = new ShaderMixinSource();
                            context.PushCompositionArray(mixin, "AttributesIndirect", __subMixin);
                            context.Mixin(__subMixin, __mixinToCompose__);
                            context.PopComposition();
                        }
                    }
                }
                if (context.GetParam(BufferToTextureKeys.AttributesTemp) != null)
                {
                    foreach(var attr in context.GetParam(BufferToTextureKeys.AttributesTemp))

                    {

                        {
                            var __mixinToCompose__ = (attr);
                            var __subMixin = new ShaderMixinSource();
                            context.PushCompositionArray(mixin, "AttributesTemp", __subMixin);
                            context.Mixin(__subMixin, __mixinToCompose__);
                            context.PopComposition();
                        }
                    }
                }
                mixin.AddMacro("IndirectReadAndStoreMacro", context.GetParam(BufferToTextureKeys.IndirectReadAndStoreMacro));
                mixin.AddMacro("IndirectStoreMacro", context.GetParam(BufferToTextureKeys.IndirectStoreMacro));
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("BufferToTextureColumnsEffect", new BufferToTextureColumnsEffect());
            }
        }
    }
}
