// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering.Voxels
{
    public static partial class ClearBufferKeys
    {
        public static readonly ObjectParameterKey<Buffer> buffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ValueParameterKey<int> offset = ParameterKeys.NewValue<int>();
    }
}
