// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class ParticleUtilitiesKeys
    {
        public static readonly ValueParameterKey<Matrix> ViewMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> ProjectionMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> ViewProjectionMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector4> ViewFrustum = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> Viewport = ParameterKeys.NewValue<Vector4>();
    }
}
