// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class ParticleBaseKeys
    {
        public static readonly ValueParameterKey<Vector4> ColorScale = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<float> AlphaAdditive = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> ZOffset = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> SoftEdgeInverseDistance = ParameterKeys.NewValue<float>();
    }
}
