// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class TemporalAntiAliasShaderKeys
    {
        public static readonly ValueParameterKey<float> u_BlendWeightMin = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> u_BlendWeightMax = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> u_HistoryBlurAmp = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> u_LumaContrastFactor = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> u_VelocityDecay = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> u_WeightCenter = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> u_WeightLowCenter = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector4> u_Weight1 = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> u_Weight2 = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> u_WeightLow1 = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> u_WeightLow2 = ParameterKeys.NewValue<Vector4>();
    }
}
