name: Build Linux

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build Configuration?
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      graphics-api:
        description: Graphics API
        default: OpenGL
        type: choice
        options:
          - OpenGL
          - Vulkan
  workflow_call:
    inputs:
      build-type:
        default: Debug
        type: string
      graphics-api:
        default: OpenGL
        type: string

jobs:
  #
  # Build Stride for Linux
  #
  Linux:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }}, ${{ github.event.inputs.graphics-api || inputs.graphics-api }})
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          msbuild build\Stride.Runtime.sln `
            -restore -m:1 -nr:false `
            -v:m -p:WarningLevel=0 `
            -p:Configuration=${{ github.event.inputs.build-type || inputs.build-type }} `
            -p:StridePlatforms=Linux `
            -p:StrideGraphicsApis=${{ github.event.inputs.graphics-api || inputs.graphics-api }} `
            -p:StrideSkipUnitTests=true `
            -p:StrideSkipAutoPack=true `
            -p:StrideEnableCodeAnalysis=true
