name: Build Windows (Full)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build Configuration
        default: Debug
        type: choice
        options:
          - Debug
          - Release
  workflow_call:
    inputs:
      build-type:
        default: Debug
        type: string

concurrency:
  group: build-windows-full-${{ github.event.pull_request.number || github.event.client_payload.pr_number || github.ref }}-${{ github.event.inputs.build-type || inputs.build-type || 'Debug' }}
  cancel-in-progress: true

jobs:
  #
  # Build Stride for Windows
  #
  Windows:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type || 'Debug' }})
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.client_payload.pr_number && format('refs/pull/{0}/merge', github.event.client_payload.pr_number) || github.ref }}
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Build
        run: |
          dotnet build build\Stride.sln `
            -nr:false `
            -v:m -p:WarningLevel=0 `
            -p:Configuration=${{ github.event.inputs.build-type || inputs.build-type || 'Debug' }} `
            -p:StridePlatforms=Windows `
            -p:StrideGraphicsApiDependentBuildAll=true `
            -p:StrideSkipUnitTests=true `
            -p:StrideSkipAutoPack=true
